name: algopath_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  collection: ^1.18.0
  freezed_annotation: ^2.4.1
  sembast: ^3.4.0+6
  sembast_web: ^2.1.0+4
  path_provider: ^2.0.11
  rxdart: ^0.28.0
  shared_preferences: ^2.3.3
  provider: ^6.0.0
  go_router: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.0.0
  freezed: ^2.0.0
  json_serializable: ^6.0.0

flutter:
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: AlgoPath
      fonts:
        - asset: fonts/AlgoPath.ttf

  uses-material-design: true
